# promise
上一章已知回调会产生控制反转问题。为了解决该问题，可以使用promise。

## 表示
```javascript
add( fetchX(),fetchY()).then(
   //完成处理函数
   function sum() {
     console.log(sum);
   },
   //拒绝处理函数
   function (err) {
     console.error(err);
   }
);

```
如果在fetchX()或fetchY()的过程中出错，或者在加法过程中出错，add()返回的就是一个被拒绝
的promise，传给then()的第二个错误处理函数回调就会从这个promise中得到拒绝值。

promise一旦完成，它就永远保持这个状态，此时它变成了不变值。

promise有两个参数,resolve和reject。resolve(...)通常标识完成，reject(...)标识拒绝。

一个promise的实现可能如下:
```javascript
function bar(fooPromise) {
  fooPromise.then(
     function() {
       //foo()已经完毕,执行bar()的任务
     },
     function() {
       //foo()出错了
     }
  )
}
```
## 鸭子类型
根据一个值的形态(具有哪些属性)对这个值的类型做出一些假定，这种类型检查叫鸭子类型。
> 如果它看起来像鸭子，叫起来像鸭子，那它一定就是鸭子
```javascript
if(p!==null&&(typeof p==='object'||typeof p==='function')&& typeof p.then==='function'){
	//是thenable
}
else {
	//不是thenable
}
```
这样实现除了有点丑之外，还有更深层次的麻烦。
如果你试图使用恰好有then()函数的一个对象或函数值完成一个promise，但不希望它被当作promise或
thenable,那就麻烦了。因为它会自动被识别为thenable，并按照特定的规则进行处理。

在ES6以前，已经有一些著名库定义了then()方法，因此会跟ES6的promise产生冲突，很不幸被降级为跟
promise不兼容。

标准决定劫持之前未保留的then，这意味着所有值，不管是过去、现在还是将来的，都不能拥有then()函数。
否则这个值在promise系统就会被认为是一个thenable,这可能导致一个难以追踪的bug。

## promise作用
回调函数可能会产生这些问题:
+ 调用回调过早；
+ 调用回调过晚（或不被调用）；
+ 调用回调次数过少或过多；
+ 未能传递所需的环境和参数；
+ 吞掉可能出现的错误和异常。
promise能解决上面的问题，promise的then()永远是异步调用的，所以不会产生调用过早的问题；
promise创建对象调用resolve()或reject()时，这个promise()的then()注册的观察回调就会被自动调度，
可以确定这些被调度的回调在下一个异步事件点上一定会被触发，因此不会产生调用过晚的问题。



## 链式流
我们可以把多个promise链接到一起完成一系列异步操作
```javascript
let p=Promise.resolve(21);
let p2=p.then(function(v) {
  console.log(v);
  return v*2;
})
p2.then(function(v) {
  console.log(v);
})
```
为了进一步阐释链接，我们可以把延迟promise创建过程一般化到一个工具中，以便在多个步骤中复用。
```javascript
function delay(time) {
  return new Promise(function(resolve,reject) {
    setTimeout(resolve,time)
  })
}
delay(100)
.then(function step2() {
  console.log('step2 after 100ms');
  return delay(200)
}).then(function step3() {
  console.log('step3 after anothor 200ms');
}).then(function step4() {
  console.log('step4 next job')
  return delay(50)
}).then(function step5() {
  console.log('step5 after anothor 50ms')
})
```
没有消息传递的延迟序列对于promise流程控制来说不是一个很有用的示例。
## 错误处理
最简单的错误处理就是try...catch，但它是同步的，不能用于异步.promise的错误用catch处理，没有使用error-first回调风格，而是使用了
分离回调(split-callback)风格。一个回调用于完成情况，一个回调用于拒绝情况。

```javascript
let p=Promise.reject('Oops');
p.then(
   function fulfilled() {
     //永远不会到达这里
   }
   function rejected(err) {
     console.log(err)
   }
)

```
## Promise模式
### Promise.all([..])
想要并行执行多个步骤，可以使用Promise.all().

Promise.all([..])返回的主promise只有在所有成员promise都完成后才会完成。如果这些promise有一个被拒绝，
主Promise.all([..])就会立即被拒绝，并丢弃来自其他promise的全部结果.
> 如果传递一个空数组,Promise.all([..])会立即完成.
## Promise.race([..])
Promise中有一个竞态,只响应第一个跨过终点线的promise.它就是Promise.race([..]).

Promise.race([..])也接收单个数组参数,这个数组由一个或多个Promise,thenable或立即值组成.
与Promise.all([ .. ]) 类似，一旦有任何一个 Promise 决议为完成，Promise.race([ .. ])
就会完成；一旦有任何一个 Promise 决议为拒绝，它就会拒绝.
> 一项竞赛至少需要一个参赛者,如果你传入一个空数组,主Promise永远不会决议.所以Promise.race([..])不要传递空数组.

## all([..])和race([..])的变体
原生ES6 Promise中提供了内建的Promise.all([..])和Promise.race([..]),但还有几种变体形式

none([..])
这个模式,所有的promise都要被拒绝,即拒绝转换为完成值.

any([..])
这个模式与all([..])类似,但是会忽略拒绝,只要完成一个而不是全部.

first([..])
这个模式类似于any([..])的竞争,只要第一个Promise完成,就会忽略后续的任何拒绝与完成.

last([..])
这个模式类似于first([..]),只有最后一个完成胜出.
## 局限性
+ 忽略错误
promise链中的错误很容易被忽略掉。如果构建了一个没有错误处理函数的Promise链,链中任何错误都会在链中
一直传播下去,直到被查看.

基本上，这等同于 try..catch 存在的局限：try..catch 可能捕获一个异常并简单地吞掉
它.所以这并不是 Promise 独有的局限性，但可能是我们希望绕过的陷阱.

+ 单一值
Promise只能有一个完成值或拒绝理由.在复杂场景,这可能是一种缺陷.
+ 无法取消的Promise

## 答案
### 链式流
1.
```javascript
//21
//42
```
## 错误处理
1.
 ```javascript
//'Oops'
```

