# promise
上一章已知回调会产生控制反转问题。为了解决该问题，可以使用promise。

## 表示
```javascript
add( fetchX(),fetchY()).then(
   //完成处理函数
   function sum() {
     console.log(sum);
   },
   //拒绝处理函数
   function (err) {
     console.error(err);
   }
);

```
如果在fetchX()或fetchY()的过程中出错，或者在加法过程中出错，add()返回的就是一个被拒绝
的promise，传给then()的第二个错误处理函数回调就会从这个promise中得到拒绝值。

promise一旦完成，它就永远保持这个状态，此时它变成了不变值。

promise有两个参数,resolve和reject。resolve(...)通常标识完成，reject(...)标识拒绝。

一个promise的实现可能如下:
```javascript
function bar(fooPromise) {
  fooPromise.then(
     function() {
       //foo()已经完毕,执行bar()的任务
     },
     function() {
       //foo()出错了
     }
  )
}
```
## 鸭子类型
根据一个值的形态(具有哪些属性)对这个值的类型做出一些假定，这种类型检查叫鸭子类型。
> 如果它看起来像鸭子，叫起来像鸭子，那它一定就是鸭子
```javascript
if(p!==null&&(typeof p==='object'||typeof p==='function')&& typeof p.then==='function'){
	//是thenable
}
else {
	//不是thenable
}
```
这样实现除了有点丑之外，还有更深层次的麻烦。
如果你试图使用恰好有then()函数的一个对象或函数值完成一个promise，但不希望它被当作promise或
thenable,那就麻烦了。因为它会自动被识别为thenable，并按照特定的规则进行处理。

在ES6以前，已经有一些著名库定义了then()方法，因此会跟ES6的promise产生冲突，很不幸被降级为跟
promise不兼容。

标准决定劫持之前未保留的then，这意味着所有值，不管是过去、现在还是将来的，都不能拥有then()函数。
否则这个值在promise系统就会被认为是一个thenable,这可能导致一个难以追踪的bug。

## promise作用
回调函数可能会产生这些问题:
+ 调用回调过早；
+ 调用回调过晚（或不被调用）；
+ 调用回调次数过少或过多；
+ 未能传递所需的环境和参数；
+ 吞掉可能出现的错误和异常。
promise能解决上面的问题，promise的then()永远是异步调用的，所以不会产生调用过早的问题；
promise创建对象调用resolve()或reject()时，这个promise()的then()注册的观察回调就会被自动调度，
可以确定这些被调度的回调在下一个异步事件点上一定会被触发，因此不会产生调用过晚的问题。

## 局限性
promise链中的错误很容易被忽略掉。